from __future__ import annotations

from pathlib import Path

from splinter.resolver import parse_target, resolve_target
from splinter.splitter import split_function



def test_split_function_in_simple_script(tmp_path: Path) -> None:
    source = tmp_path / "main.py"
    source.write_text(
        "import math\n\n"
        "def area(r):\n"
        "    return math.pi * r * r\n\n"
        "def hello(name):\n"
        "    return f'Hello, {name}'\n",
        encoding="utf-8",
    )

    resolved = resolve_target(parse_target("main.area"), cwd=tmp_path)
    result = split_function(resolved)

    assert result.new_module_file.exists()
    assert "from modules import area" in source.read_text(encoding="utf-8")
    assert "def area" not in source.read_text(encoding="utf-8")

    extracted = result.new_module_file.read_text(encoding="utf-8")
    assert "import math" in extracted
    assert "def area(r):" in extracted



def test_split_function_in_package_module(tmp_path: Path) -> None:
    pkg = tmp_path / "app"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("", encoding="utf-8")
    mod = pkg / "service.py"
    mod.write_text(
        "\"\"\"Service helpers.\"\"\"\n\n"
        "import json\n\n"
        "def encode(data):\n"
        "    return json.dumps(data)\n\n"
        "def untouched():\n"
        "    return 1\n",
        encoding="utf-8",
    )

    resolved = resolve_target(parse_target("app.service.encode"), cwd=tmp_path)
    result = split_function(resolved)

    updated = mod.read_text(encoding="utf-8")
    assert "from .modules import encode" in updated
    assert "def encode" not in updated
    assert "def untouched" in updated

    extracted = result.new_module_file.read_text(encoding="utf-8")
    assert '"""Auto-generated by Splinter from service.py."""' in extracted
    assert "import json" in extracted



def test_split_function_copies_top_level_dependencies(tmp_path: Path) -> None:
    source = tmp_path / "main.py"
    source.write_text(
        "from __future__ import annotations\n\n"
        "import json\n"
        "from dataclasses import dataclass\n"
        "from pathlib import Path\n"
        "from typing import Any\n\n"
        "CACHE: dict[str, Any] = {}\n\n"
        "@dataclass\n"
        "class User:\n"
        "    id: int\n"
        "    name: str\n"
        "    scores: list[int]\n\n"
        "def normalize_name(name: str) -> str:\n"
        "    return name.strip().title()\n\n"
        "def load_users(path: str) -> list[User]:\n"
        "    raw = json.loads(Path(path).read_text(encoding='utf-8'))\n"
        "    users = [\n"
        "        User(\n"
        "            id=item['id'],\n"
        "            name=normalize_name(item['name']),\n"
        "            scores=item.get('scores', []),\n"
        "        )\n"
        "        for item in raw\n"
        "    ]\n"
        "    CACHE['users'] = users\n"
        "    return users\n",
        encoding="utf-8",
    )

    resolved = resolve_target(parse_target("main.load_users"), cwd=tmp_path)
    result = split_function(resolved)

    extracted = result.new_module_file.read_text(encoding="utf-8")
    assert "CACHE: dict[str, Any] = {}" in extracted
    assert "@dataclass" in extracted
    assert "class User:" in extracted
    assert "def normalize_name(name: str) -> str:" in extracted
    assert "def load_users(path: str) -> list[User]:" in extracted



def test_split_function_merges_package_imports_and_updates_init(tmp_path: Path) -> None:
    source = tmp_path / "main.py"
    source.write_text(
        "def area(r):\n"
        "    return r * r\n\n"
        "def hello(name):\n"
        "    return f'Hello, {name}'\n\n"
        "def orchestrate(value, name):\n"
        "    return area(value), hello(name)\n",
        encoding="utf-8",
    )

    area_result = split_function(resolve_target(parse_target("main.area"), cwd=tmp_path))
    hello_result = split_function(resolve_target(parse_target("main.hello"), cwd=tmp_path))

    updated = source.read_text(encoding="utf-8")
    assert "from modules import area, hello" in updated
    assert "from modules.area import area" not in updated
    assert "from modules.hello import hello" not in updated

    init_text = (tmp_path / "modules" / "__init__.py").read_text(encoding="utf-8")
    assert "from .area import area" in init_text
    assert "from .hello import hello" in init_text

    assert area_result.new_module_file.exists()
    assert hello_result.new_module_file.exists()


def test_split_function_preview_does_not_write_files(tmp_path: Path) -> None:
    source = tmp_path / "main.py"
    original = (
        "import math\n\n"
        "def area(r):\n"
        "    return math.pi * r * r\n\n"
        "def hello(name):\n"
        "    return f'Hello, {name}'\n"
    )
    source.write_text(original, encoding="utf-8")

    resolved = resolve_target(parse_target("main.area"), cwd=tmp_path)
    result = split_function(resolved, preview=True)

    assert result.preview is True
    assert "from modules import area" in result.module_text
    assert "def area(r):" in result.new_module_text
    assert "from .area import area\n" == result.init_text
    assert source.read_text(encoding="utf-8") == original
    assert not result.new_module_file.exists()
    assert not result.init_file.exists()
