from __future__ import annotations

import ast
import difflib
import fnmatch
from dataclasses import dataclass
from pathlib import Path

from .analysis import statement_start_lineno
from .exceptions import PySplitError
from .models import FileChange
from .rewrite import extract_lines, validate_split_outputs
from .utils import read_python_source, write_text_preserving_newlines


@dataclass(slots=True)
class ParadigmOptions:
    preview: bool = False
    class_name: str | None = None
    validate: bool = False
    include_patterns: list[str] | None = None
    exclude_patterns: list[str] | None = None
    public_only: bool = False


@dataclass(slots=True)
class ParadigmResult:
    module_file: Path
    class_name: str
    function_names: list[str]
    skipped: dict[str, str]
    preview: bool
    file_changes: list[FileChange]
    preview_diffs: list[str]


FUNCTIONAL_MARKER = "# Auto-generated by ManaSplice: functional facade"
EVENT_MARKER = "# Auto-generated by ManaSplice: event facade"


def transform_module_to_oop(file_path: Path, *, options: ParadigmOptions | None = None) -> ParadigmResult:
    options = options or ParadigmOptions()
    source_text = read_python_source(file_path)
    try:
        tree = ast.parse(source_text)
    except SyntaxError as exc:
        raise PySplitError(f"Could not parse '{file_path}': {exc}") from exc

    class_name = options.class_name or _default_class_name(file_path)
    if not class_name.isidentifier():
        raise PySplitError(f"Invalid class name '{class_name}'.")
    if _has_top_level_class(tree, class_name):
        raise PySplitError(f"Class '{class_name}' already exists in '{file_path}'.")

    candidates = _collect_candidates(tree, options)
    transformable = [candidate for candidate in candidates if not candidate.skip_reason]
    skipped = {candidate.node.name: candidate.skip_reason for candidate in candidates if candidate.skip_reason}

    if not transformable:
        return ParadigmResult(
            module_file=file_path,
            class_name=class_name,
            function_names=[],
            skipped=skipped,
            preview=options.preview,
            file_changes=[],
            preview_diffs=[],
        )

    updated_source = _rewrite_source(source_text, tree, transformable, class_name)
    file_changes = [FileChange(file_path, True, source_text, updated_source)]
    if options.validate:
        validate_split_outputs(file_changes)
    if not options.preview:
        write_text_preserving_newlines(file_path, updated_source)

    return ParadigmResult(
        module_file=file_path,
        class_name=class_name,
        function_names=[candidate.node.name for candidate in transformable],
        skipped=skipped,
        preview=options.preview,
        file_changes=file_changes,
        preview_diffs=_build_preview_diffs(file_changes),
    )


def transform_module_to_functional(file_path: Path, *, options: ParadigmOptions | None = None) -> ParadigmResult:
    options = options or ParadigmOptions()
    source_text, tree = _parse_source(file_path)
    candidates = _collect_candidates(tree, options)
    selected = [candidate for candidate in candidates if not candidate.skip_reason]
    skipped = {candidate.node.name: candidate.skip_reason for candidate in candidates if candidate.skip_reason}

    if FUNCTIONAL_MARKER in source_text:
        return _empty_result(file_path, "FUNCTIONAL_API", skipped, options.preview)
    if not selected:
        return _empty_result(file_path, "FUNCTIONAL_API", skipped, options.preview)
    _ensure_names_available(tree, file_path, {"compose_functions", "pipe", "FUNCTIONAL_API"})

    names = [candidate.node.name for candidate in selected]
    updated_source = _append_generated_block(source_text, _build_functional_facade(names))
    return _write_paradigm_result(
        file_path=file_path,
        before_text=source_text,
        after_text=updated_source,
        class_name="FUNCTIONAL_API",
        function_names=names,
        skipped=skipped,
        options=options,
    )


def transform_module_to_event_driven(file_path: Path, *, options: ParadigmOptions | None = None) -> ParadigmResult:
    options = options or ParadigmOptions()
    source_text, tree = _parse_source(file_path)
    candidates = _collect_candidates(tree, options)
    selected = [candidate for candidate in candidates if not candidate.skip_reason]
    skipped = {candidate.node.name: candidate.skip_reason for candidate in candidates if candidate.skip_reason}

    if EVENT_MARKER in source_text:
        return _empty_result(file_path, "EVENT_HANDLERS", skipped, options.preview)
    if not selected:
        return _empty_result(file_path, "EVENT_HANDLERS", skipped, options.preview)
    _ensure_names_available(tree, file_path, {"EVENT_HANDLERS", "dispatch_event"})

    names = [candidate.node.name for candidate in selected]
    updated_source = _append_generated_block(source_text, _build_event_facade(names))
    return _write_paradigm_result(
        file_path=file_path,
        before_text=source_text,
        after_text=updated_source,
        class_name="EVENT_HANDLERS",
        function_names=names,
        skipped=skipped,
        options=options,
    )


def transform_module_to_procedural(file_path: Path, *, options: ParadigmOptions | None = None) -> ParadigmResult:
    options = options or ParadigmOptions()
    source_text, tree = _parse_source(file_path)
    class_name = options.class_name or _default_class_name(file_path)
    target_class = next(
        (stmt for stmt in tree.body if isinstance(stmt, ast.ClassDef) and stmt.name == class_name),
        None,
    )
    if target_class is None:
        return _empty_result(file_path, class_name, {}, options.preview)

    methods = _collect_static_methods(target_class, file_path)
    if not methods:
        return _empty_result(file_path, class_name, {}, options.preview)

    method_names = {method.name for method in methods}
    top_level_wrappers = [
        stmt
        for stmt in tree.body
        if isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef))
        and stmt.name in method_names
        and _is_generated_oop_wrapper(stmt, class_name)
    ]
    conflicts = [
        stmt.name
        for stmt in tree.body
        if isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef))
        and stmt.name in method_names
        and stmt not in top_level_wrappers
    ]
    if conflicts:
        raise PySplitError(
            f"Refusing procedural transform for '{file_path}' because top-level function(s) already exist: "
            f"{', '.join(sorted(conflicts))}."
        )

    updated_source = _rewrite_oop_class_to_procedural(
        source_text,
        class_node=target_class,
        methods=methods,
        wrappers=top_level_wrappers,
    )
    return _write_paradigm_result(
        file_path=file_path,
        before_text=source_text,
        after_text=updated_source,
        class_name=class_name,
        function_names=[method.name for method in methods],
        skipped={},
        options=options,
    )


def _parse_source(file_path: Path) -> tuple[str, ast.Module]:
    source_text = read_python_source(file_path)
    try:
        return source_text, ast.parse(source_text)
    except SyntaxError as exc:
        raise PySplitError(f"Could not parse '{file_path}': {exc}") from exc


def _empty_result(file_path: Path, class_name: str, skipped: dict[str, str], preview: bool) -> ParadigmResult:
    return ParadigmResult(
        module_file=file_path,
        class_name=class_name,
        function_names=[],
        skipped=skipped,
        preview=preview,
        file_changes=[],
        preview_diffs=[],
    )


def _write_paradigm_result(
    *,
    file_path: Path,
    before_text: str,
    after_text: str,
    class_name: str,
    function_names: list[str],
    skipped: dict[str, str],
    options: ParadigmOptions,
) -> ParadigmResult:
    file_changes = [FileChange(file_path, True, before_text, after_text)]
    if options.validate:
        validate_split_outputs(file_changes)
    if not options.preview:
        write_text_preserving_newlines(file_path, after_text)

    return ParadigmResult(
        module_file=file_path,
        class_name=class_name,
        function_names=function_names,
        skipped=skipped,
        preview=options.preview,
        file_changes=file_changes,
        preview_diffs=_build_preview_diffs(file_changes),
    )


@dataclass(slots=True)
class _FunctionCandidate:
    node: ast.FunctionDef | ast.AsyncFunctionDef
    start_lineno: int
    end_lineno: int
    skip_reason: str


def _collect_candidates(tree: ast.Module, options: ParadigmOptions) -> list[_FunctionCandidate]:
    candidates: list[_FunctionCandidate] = []
    include_patterns = options.include_patterns or []
    exclude_patterns = options.exclude_patterns or []
    overloaded_names = {
        stmt.name
        for stmt in tree.body
        if isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef)) and _is_overload_function(stmt)
    }
    eager_references = _collect_eager_top_level_references(tree)

    for stmt in tree.body:
        if not isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if _is_overload_function(stmt):
            continue
        if options.public_only and stmt.name.startswith("_"):
            continue
        if include_patterns and not any(fnmatch.fnmatchcase(stmt.name, pattern) for pattern in include_patterns):
            continue
        if exclude_patterns and any(fnmatch.fnmatchcase(stmt.name, pattern) for pattern in exclude_patterns):
            continue
        if stmt.end_lineno is None:
            raise PySplitError(f"Could not determine end line for function '{stmt.name}'.")

        skip_reason = ""
        if stmt.decorator_list:
            skip_reason = "decorated functions are left unchanged"
        elif stmt.name in overloaded_names:
            skip_reason = "overloaded functions are left unchanged"
        elif _has_multiline_string_literal(stmt):
            skip_reason = "functions with multiline string literals are left unchanged"
        elif stmt.name in eager_references:
            skip_reason = "functions referenced during module initialization are left unchanged"
        candidates.append(
            _FunctionCandidate(
                node=stmt,
                start_lineno=statement_start_lineno(stmt),
                end_lineno=stmt.end_lineno,
                skip_reason=skip_reason,
            )
        )

    return candidates


def _has_multiline_string_literal(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    for child in ast.walk(node):
        if isinstance(child, ast.Constant) and isinstance(child.value, str):
            if getattr(child, "end_lineno", child.lineno) > child.lineno:
                return True
        if isinstance(child, ast.JoinedStr) and getattr(child, "end_lineno", child.lineno) > child.lineno:
            return True
    return False


def _collect_eager_top_level_references(tree: ast.Module) -> set[str]:
    references: set[str] = set()
    for stmt in tree.body:
        if isinstance(stmt, (ast.Import, ast.ImportFrom, ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if _is_main_guard(stmt):
            continue
        references.update(_loaded_names(stmt))
    return references


def _loaded_names(node: ast.AST) -> set[str]:
    return {child.id for child in ast.walk(node) if isinstance(child, ast.Name) and isinstance(child.ctx, ast.Load)}


def _ensure_names_available(tree: ast.Module, file_path: Path, names: set[str]) -> None:
    existing = {
        stmt.name
        for stmt in tree.body
        if isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
    }
    for stmt in tree.body:
        if isinstance(stmt, (ast.Assign, ast.AnnAssign, ast.AugAssign)):
            existing.update(_assigned_names(stmt))
    collisions = sorted(existing & names)
    if collisions:
        raise PySplitError(
            f"Refusing to generate facade in '{file_path}' because name(s) already exist: {', '.join(collisions)}."
        )


def _assigned_names(node: ast.AST) -> list[str]:
    targets: list[ast.AST] = []
    if isinstance(node, ast.Assign):
        targets = list(node.targets)
    elif isinstance(node, ast.AnnAssign):
        targets = [node.target]
    elif isinstance(node, ast.AugAssign):
        targets = [node.target]
    return [child.id for target in targets for child in ast.walk(target) if isinstance(child, ast.Name)]


def _rewrite_source(
    source_text: str,
    tree: ast.Module,
    candidates: list[_FunctionCandidate],
    class_name: str,
) -> str:
    candidates = sorted(candidates, key=lambda candidate: candidate.start_lineno)
    lines = source_text.splitlines(keepends=True)
    class_block = _build_class_block(source_text, candidates, class_name)
    insertion_lineno = _generated_class_insertion_lineno(tree, len(lines))

    output: list[str] = []
    cursor = 1
    inserted_class = False
    for candidate in candidates:
        if not inserted_class and cursor <= insertion_lineno <= candidate.start_lineno:
            output.extend(lines[cursor - 1 : insertion_lineno - 1])
            output.append(class_block)
            cursor = insertion_lineno
            inserted_class = True
        output.extend(lines[cursor - 1 : candidate.start_lineno - 1])
        output.append(_build_wrapper(candidate.node, class_name))
        cursor = candidate.end_lineno + 1
    if not inserted_class:
        output.extend(lines[cursor - 1 : insertion_lineno - 1])
        output.append(class_block)
        cursor = insertion_lineno
    output.extend(lines[cursor - 1 :])

    return _normalize_rewritten_source("".join(output))


def _generated_class_insertion_lineno(tree: ast.Module, line_count: int) -> int:
    for stmt in tree.body:
        if _is_main_guard(stmt):
            return statement_start_lineno(stmt)
    return line_count + 1


def _is_main_guard(stmt: ast.stmt) -> bool:
    if not isinstance(stmt, ast.If):
        return False
    test = stmt.test
    if not isinstance(test, ast.Compare) or len(test.ops) != 1 or len(test.comparators) != 1:
        return False
    if not isinstance(test.ops[0], ast.Eq):
        return False
    left = test.left
    right = test.comparators[0]
    return (
        isinstance(left, ast.Name)
        and left.id == "__name__"
        and isinstance(right, ast.Constant)
        and right.value == "__main__"
    )


def _build_class_block(source_text: str, candidates: list[_FunctionCandidate], class_name: str) -> str:
    methods = []
    for candidate in candidates:
        block = extract_lines(source_text, candidate.start_lineno, candidate.end_lineno).lstrip("\r\n").rstrip()
        methods.append("    @staticmethod\n" + _indent(block, "    "))
    return f"class {class_name}:\n" + "\n\n".join(methods) + "\n\n"


def _build_wrapper(node: ast.FunctionDef | ast.AsyncFunctionDef, class_name: str) -> str:
    async_prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    await_prefix = "await " if isinstance(node, ast.AsyncFunctionDef) else ""
    returns = f" -> {ast.unparse(node.returns)}" if node.returns is not None else ""
    signature = ast.unparse(node.args)
    call_args = _call_arguments(node.args)
    call = f"{await_prefix}{class_name}.{node.name}({call_args})"
    return f"{async_prefix}def {node.name}({signature}){returns}:\n    return {call}\n\n"


def _build_functional_facade(function_names: list[str]) -> str:
    mapping = "\n".join(f'    "{name}": {name},' for name in sorted(function_names))
    return (
        f"{FUNCTIONAL_MARKER}\n"
        "def compose_functions(*functions):\n"
        "    def composed(value):\n"
        "        result = value\n"
        "        for function in reversed(functions):\n"
        "            result = function(result)\n"
        "        return result\n\n"
        "    return composed\n\n\n"
        "def pipe(value, *functions):\n"
        "    result = value\n"
        "    for function in functions:\n"
        "        result = function(result)\n"
        "    return result\n\n\n"
        "FUNCTIONAL_API = {\n"
        f"{mapping}\n"
        "}\n"
    )


def _build_event_facade(function_names: list[str]) -> str:
    mapping = "\n".join(f'    "{name}": {name},' for name in sorted(function_names))
    return (
        f"{EVENT_MARKER}\n"
        "EVENT_HANDLERS = {\n"
        f"{mapping}\n"
        "}\n\n\n"
        "def dispatch_event(event_name, *args, **kwargs):\n"
        "    try:\n"
        "        handler = EVENT_HANDLERS[event_name]\n"
        "    except KeyError as exc:\n"
        "        raise ValueError(f\"Unknown event: {event_name}\") from exc\n"
        "    return handler(*args, **kwargs)\n"
    )


def _append_generated_block(source_text: str, block: str) -> str:
    return source_text.rstrip() + "\n\n\n" + block


def _collect_static_methods(class_node: ast.ClassDef, file_path: Path) -> list[ast.FunctionDef | ast.AsyncFunctionDef]:
    methods: list[ast.FunctionDef | ast.AsyncFunctionDef] = []
    for stmt in class_node.body:
        if isinstance(stmt, ast.Pass):
            continue
        if not isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef)):
            raise PySplitError(
                f"Refusing procedural transform for '{file_path}' because "
                f"'{class_node.name}' contains non-method code."
            )
        decorators = {_decorator_name(decorator) for decorator in stmt.decorator_list}
        if decorators != {"staticmethod"}:
            raise PySplitError(
                f"Refusing procedural transform for '{file_path}' because '{class_node.name}.{stmt.name}' "
                "is not a plain @staticmethod."
            )
        if stmt.end_lineno is None:
            raise PySplitError(f"Could not determine end line for method '{class_node.name}.{stmt.name}'.")
        methods.append(stmt)
    return methods


def _is_generated_oop_wrapper(node: ast.FunctionDef | ast.AsyncFunctionDef, class_name: str) -> bool:
    if len(node.body) != 1 or not isinstance(node.body[0], ast.Return):
        return False
    value = node.body[0].value
    if isinstance(value, ast.Await):
        value = value.value
    if not isinstance(value, ast.Call) or not isinstance(value.func, ast.Attribute):
        return False
    if not isinstance(value.func.value, ast.Name) or value.func.value.id != class_name:
        return False
    return value.func.attr == node.name


def _rewrite_oop_class_to_procedural(
    source_text: str,
    *,
    class_node: ast.ClassDef,
    methods: list[ast.FunctionDef | ast.AsyncFunctionDef],
    wrappers: list[ast.FunctionDef | ast.AsyncFunctionDef],
) -> str:
    ranges_to_remove = {(statement_start_lineno(class_node), class_node.end_lineno or class_node.lineno)}
    ranges_to_remove.update(
        (statement_start_lineno(wrapper), wrapper.end_lineno or wrapper.lineno) for wrapper in wrappers
    )
    lines = source_text.splitlines(keepends=True)
    method_block = "\n\n".join(_method_to_function_block(lines, method).strip() for method in methods) + "\n\n"

    output: list[str] = []
    cursor = 1
    inserted_methods = False
    for start_lineno, end_lineno in sorted(ranges_to_remove):
        output.extend(lines[cursor - 1 : start_lineno - 1])
        if start_lineno == statement_start_lineno(class_node) and not inserted_methods:
            output.append(method_block)
            inserted_methods = True
        cursor = end_lineno + 1
    output.extend(lines[cursor - 1 :])
    output.append(_build_procedural_compat_class(class_node.name, [method.name for method in methods]))
    return _normalize_rewritten_source("".join(output))


def _method_to_function_block(lines: list[str], method: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    start = statement_start_lineno(method)
    block_lines = lines[start - 1 : method.end_lineno]
    stripped_decorator_lines = [line for line in block_lines if line.strip() != "@staticmethod"]
    return "".join(_dedent_one_level(line) for line in stripped_decorator_lines)


def _dedent_one_level(line: str) -> str:
    if line.startswith("    "):
        return line[4:]
    return line


def _build_procedural_compat_class(class_name: str, function_names: list[str]) -> str:
    assignments = "\n".join(f"    {name} = staticmethod({name})" for name in sorted(function_names))
    return f"\n\nclass {class_name}:\n{assignments}\n"


def _call_arguments(args: ast.arguments) -> str:
    names: list[str] = []
    names.extend(arg.arg for arg in args.posonlyargs)
    names.extend(arg.arg for arg in args.args)
    if args.vararg is not None:
        names.append(f"*{args.vararg.arg}")
    names.extend(f"{arg.arg}={arg.arg}" for arg in args.kwonlyargs)
    if args.kwarg is not None:
        names.append(f"**{args.kwarg.arg}")
    return ", ".join(names)


def _default_class_name(file_path: Path) -> str:
    stem = file_path.stem
    if stem == "__init__":
        stem = file_path.parent.name
    words = [word for word in stem.replace("-", "_").split("_") if word]
    base = "".join(word[:1].upper() + word[1:] for word in words) or "Module"
    return f"{base}Operations"


def _has_top_level_class(tree: ast.Module, class_name: str) -> bool:
    return any(isinstance(stmt, ast.ClassDef) and stmt.name == class_name for stmt in tree.body)


def _is_overload_function(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    return any(_decorator_name(decorator) == "overload" for decorator in node.decorator_list)


def _decorator_name(node: ast.expr) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    if isinstance(node, ast.Call):
        return _decorator_name(node.func)
    return ""


def _indent(text: str, prefix: str) -> str:
    return "".join(prefix + line if line.strip() else line for line in text.splitlines(keepends=True))


def _normalize_rewritten_source(source_text: str) -> str:
    updated = source_text
    while "\n\n\n" in updated:
        updated = updated.replace("\n\n\n", "\n\n")
    return updated.lstrip("\n")


def _build_preview_diffs(file_changes: list[FileChange]) -> list[str]:
    diffs: list[str] = []
    for change in file_changes:
        diff_lines = list(
            difflib.unified_diff(
                change.before_text.splitlines(),
                change.after_text.splitlines(),
                fromfile=str(change.path),
                tofile=str(change.path),
                lineterm="",
            )
        )
        if diff_lines:
            diffs.append("\n".join(diff_lines))
    return diffs
